import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
// import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import NavBar from "./Component/NavBar";
import Footer from "./Component/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body >
        <div>
          <div>
            <NavBar />
          </div>
          <div>
            {children}
          </div>
          <div id="footer">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  )
}